version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npx expo export --platform web
  artifacts:
    baseDirectory: dist  # or web-build, depending on your Expo version
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
